### ISSUE TITLE
Cannot download CRL path

### ISSUE THREAD

**Issue by ski14** [damianofalcioni/Websocket-Smart-Card-Signer#7]
Sir can you please check my edited files from the link below...I cannot perform any signature  :(

https://drive.google.com/open?id=11933odcacOJtmuXilMyCuBpVNFYw6F27

**Comment by damianofalcioni** [comment]
Hi,
as said in the past issue the problem is in your java keystore and not in the project. 
I provided you the instructions to look on for adding the certificate in your keystore in order to fix the chain validation problem.

Here I don't know if the problem is the same or what should I look in your code.
Also, we are on GitHub and I did not understand why you did not share your code as a fork of mine in your repository so I can easily check your changes.
In addition, as I understood, you use a token that I did not have and never tested, so for sure I can not recreate your issue locally!
